#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App3.Resource", IsApplication=true)]

namespace App3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int fade = 2131034112;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int words = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int black = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int blue = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int red = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int white = 2131165186;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_horizontal_margin = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int activity_vertical_margin = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android_hangman_arm1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int android_hangman_arm2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int android_hangman_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int android_hangman_body = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int android_hangman_gallows = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int android_hangman_head = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int android_hangman_help = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int android_hangman_leg1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int android_hangman_leg2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int letter_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int letter_down = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int letter_up = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int new_hangman_ic = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0008
			public const int arm1 = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int arm2 = 2131361801;
			
			// aapt resource value: 0x7f0a0007
			public const int body = 2131361799;
			
			// aapt resource value: 0x7f0a000f
			public const int btnback = 2131361807;
			
			// aapt resource value: 0x7f0a0004
			public const int btnhigh = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int btnplay = 2131361797;
			
			// aapt resource value: 0x7f0a000e
			public const int edt = 2131361806;
			
			// aapt resource value: 0x7f0a0006
			public const int head = 2131361798;
			
			// aapt resource value: 0x7f0a0010
			public const int img = 2131361808;
			
			// aapt resource value: 0x7f0a000a
			public const int leg1 = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int leg2 = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int letters = 2131361805;
			
			// aapt resource value: 0x7f0a0003
			public const int lv = 2131361795;
			
			// aapt resource value: 0x7f0a0000
			public const int rl = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int txt = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int vi = 2131361794;
			
			// aapt resource value: 0x7f0a000c
			public const int word = 2131361804;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int category = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int exit = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int letter = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int next = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int score = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int splash = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090002
			public const int action_settings = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int arm = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int body = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int gallows = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int head = 2131296261;
			
			// aapt resource value: 0x7f090000
			public const int hello = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int leg = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int play = 2131296259;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
